### ISSUE TITLE
Spacing, Desktop

### ISSUE THREAD

**Issue by katie-uglywolf** [the-ugly-wolf/the-ugly-wolf.github.io#5]
Remove ~10-20px from the top and place at the bottom of "Los Angeles". Keep the pink height the same just take some spacing from the top and put it at the bottom.

**Comment by katie-uglywolf** [comment]
More clarity— 

It should look like this but the black bar on this image should be pink. 

![screen shot 2018-12-02 at 1 50 42 pm](https://user-images.githubusercontent.com/41439130/49345414-49693300-f639-11e8-9403-c9635940401e.png)

**Comment by b-cooper** [comment]
Closed by d40b2bc084837a51f62d0ad7235565c4c409b39f
